alias diff='diff -ubwt'
alias ica='/opt/Citrix/ICAClient/wfica -icaroot /opt/Citrix/ICAClient'
alias lesc='less -SC'
alias llt='ls -altr'
alias od='od -A o -t co1 -v'
alias piconn='sudo screen /dev/ttyUSB0 115200'
alias vim='vim -p'
alias yapf='/usr/bin/yapf3 --style $HOME/.style.yapf'
